version: '3.8'
services:
  linktree:
    container_name: linktree
    image: built-linktree
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --insecure --fail https://localhost:443/health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "/etc/letsencrypt/archive/creeper6530.tplinkdns.com:/certs/archive/creeper6530.tplinkdns.com:ro"
    - "/etc/letsencrypt/live/creeper6530.tplinkdns.com:/certs/live/creeper6530.tplinkdns.com:ro"